# Generated by Django 5.2.7 on 2025-10-02 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('limite_horas', models.PositiveIntegerField(default=0)),
                ('regras_documentais', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id_atividade', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('horas_solicitadas', models.PositiveIntegerField(default=0)),
                ('horas_concedidas', models.PositiveIntegerField(blank=True, null=True)),
                ('vinculo', models.CharField(blank=True, max_length=255, null=True)),
                ('contato_responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Enviado', 'Enviado'), ('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Aprovado com ajuste', 'Aprovado com ajuste'), ('Indeferido', 'Indeferido'), ('Complementação solicitada', 'Complementação solicitada'), ('Computado', 'Computado')], default='Enviado', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='activities.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id_extrato', models.AutoField(primary_key=True, serialize=False)),
                ('horas_computadas', models.PositiveIntegerField(default=0)),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extrato', to='activities.atividade')),
            ],
        ),
    ]
