# Generated by Django 5.1.1 on 2025-10-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('local', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de término')),
                ('horas_solicitadas', models.PositiveIntegerField(default=0, verbose_name='Horas solicitadas')),
                ('horas_concedidas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas concedidas')),
                ('documentos', models.JSONField(blank=True, null=True, verbose_name='Documentos')),
                ('checklist', models.JSONField(blank=True, null=True, verbose_name='Checklist')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa')),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Enviado', 'Enviado'), ('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Aprovado com ajuste', 'Aprovado com ajuste'), ('Indeferido', 'Indeferido'), ('Complementação solicitada', 'Complementação solicitada'), ('Computado', 'Computado')], default='Enviado', max_length=50, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('limite_horas', models.PositiveIntegerField(default=0, verbose_name='Limite de horas')),
                ('regras', models.JSONField(blank=True, null=True, verbose_name='Regras')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
