# Generated by Django 5.2.7 on 2025-10-02 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('limit_hours', models.PositiveIntegerField(default=0)),
                ('rules', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='extrato',
            name='atividade',
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hours_requested', models.PositiveIntegerField(default=0)),
                ('hours_granted', models.PositiveIntegerField(blank=True, null=True)),
                ('documents', models.JSONField(blank=True, null=True)),
                ('checklist', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Enviado', 'Enviado'), ('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Aprovado com ajuste', 'Aprovado com ajuste'), ('Indeferido', 'Indeferido'), ('Complementação solicitada', 'Complementação solicitada'), ('Computado', 'Computado')], default='Enviado', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='Extrato',
        ),
    ]
