# Generated by Django 5.1.1 on 2025-10-24 19:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Notificacao',
        ),
    ]
