# Generated by Django 5.1.1 on 2025-11-08 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_rename_notification_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracoesInstituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_minima', models.PositiveIntegerField(default=200, verbose_name='Carga mínima total')),
                ('periodo_maximo', models.PositiveIntegerField(default=12, verbose_name='Período máximo')),
            ],
            options={
                'verbose_name': 'Configuração da Instituição',
                'verbose_name_plural': 'Configurações da Instituição',
            },
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='documentos',
        ),
        migrations.AddField(
            model_name='atividade',
            name='avaliado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_avaliadas', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado por'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='contato',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contato responsável'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='vinculo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vínculo (projeto/evento)'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='data_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Data limite'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='obrigatoriedade',
            field=models.BooleanField(default=False, verbose_name='Obrigatoriedade'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='periodo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades', to='activities.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='checklist',
            field=models.JSONField(blank=True, null=True, verbose_name='Checklist de complementação'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='status',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Enviado', 'Enviado'), ('Em análise', 'Em análise'), ('Complementação solicitada', 'Complementação solicitada'), ('Aprovado', 'Aprovado'), ('Aprovado com ajuste', 'Aprovado com ajuste'), ('Indeferido', 'Indeferido'), ('Computado', 'Computado')], default='Rascunho', max_length=50, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='AtividadeArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='atividades/arquivos/', verbose_name='Arquivo')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='activities.atividade')),
            ],
            options={
                'verbose_name': 'Arquivo de Atividade',
                'verbose_name_plural': 'Arquivos de Atividades',
            },
        ),
        migrations.CreateModel(
            name='AtividadeComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='activities.atividade')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário de Atividade',
                'verbose_name_plural': 'Comentários de Atividades',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AtividadeHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=50, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(max_length=50, verbose_name='Status Novo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentário')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='activities.atividade')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Atividade',
                'verbose_name_plural': 'Históricos de Atividades',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255, verbose_name='Ação')),
                ('antes', models.TextField(blank=True, verbose_name='Antes')),
                ('depois', models.TextField(blank=True, verbose_name='Depois')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
            },
        ),
    ]
