# Generated by Django 5.1.1 on 2025-11-23 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_add_initial_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('nova_atividade', 'Nova atividade enviada'), ('complementacao_solicitada', 'Complementação solicitada'), ('decisao', 'Decisão sobre atividade'), ('meta_atingida', 'Meta de horas atingida'), ('novo_relatorio', 'Novo relatório enviado')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to='relatorios/%Y/%m/', verbose_name='Arquivo')),
                ('status', models.CharField(choices=[('Enviado', 'Enviado'), ('Em análise', 'Em análise'), ('Complementação solicitada', 'Complementação solicitada'), ('Aprovado', 'Aprovado'), ('Aprovado com ajuste', 'Aprovado com ajuste'), ('Indeferido', 'Indeferido'), ('Computado', 'Computado')], default='Enviado', max_length=50, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa (quando indeferido)')),
                ('checklist', models.JSONField(blank=True, null=True, verbose_name='Checklist de complementação')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios', to='activities.atividade', verbose_name='Atividade vinculada')),
                ('avaliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_avaliados', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado por')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='activities.relatorio')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário de Relatório',
                'verbose_name_plural': 'Comentários de Relatórios',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=50, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(max_length=50, verbose_name='Status Novo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentário')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='activities.relatorio')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Relatório',
                'verbose_name_plural': 'Históricos de Relatórios',
                'ordering': ['-timestamp'],
            },
        ),
    ]
